name: assign
on: [pull_request, pull_request_target, workflow_dispatch]
permissions:
  issues: write
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.event_name, 'pull_request')
        uses: actions/github-script@v7
        with:
          script: |
            const {data: repo} = await github.rest.repos.get(context.repo)
            if (!repo.has_issues) return
            const num = context.payload.pull_request?.number
            if (!num) return
            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: num,
              assignees: ["Lombardoh"]
            })
