name: assign
on: [pull_request, pull_request_target, workflow_dispatch]
permissions: {}
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.event_name, 'pull_request')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ASSIGN_TOKEN }}
          script: |
            const n = context.payload.pull_request.number
            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: n,
              assignees: ["Lombardoh"]
            })
